### ISSUE TITLE
Fatal error: Uncaught OutOfRangeException

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#651]
### ***Debug lvl 2***
```
[11:56:55] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Iron Sword (267:0)x1
[11:56:55] [Server thread/INFO]: somekidonmyserver picked up and placed: Item Iron Sword (267:0)x1

Fatal error: Uncaught OutOfRangeException: Items array size cannot be greater than 10. in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php:599
Stack trace:
#0 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(2010): pocketmine\Player->addPickedupItem(Object(pocketmine\item\IronSword))
#1 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/inventory/SimpleTransactionGroup.php(153): pocketmine\Player->processContainerChange(Object(pocketmine\inventory\PlayerInventory), 0, Object(pocketmine\item\ItemBlock), Object(pocketmine\item\IronSword))
#2 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(3280): pocketmine\inventory\SimpleTransactionGroup->execute()
#3 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/network/Network.php(218): pocketmine\Player->handleDataPacket(Object(pocketmine\network\protocol\ContainerSetSlotPacket))
#4 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/po in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php on line 599
[11:56:55] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[11:56:55] [Server thread/EMERGENCY]: Please upload the "C:\Users\hello\Desktop\Network\crashdumps/CrashDump_Fri_Aug_5-11.56.55-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
### ***Crashdump***
```
Error: Uncaught OutOfRangeException: Items array size cannot be greater than 10. in phar://C:/Users/hallo/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php:599
File: /src/pocketmine/Player
Line: 599
Type: E_ERROR

Code:
[590] 	 *
[591] 	 * @return permission\PermissionAttachmentInfo[]
[592] 	 */
[593] 	public function getEffectivePermissions(){
[594] 		return $this->perm->getEffectivePermissions();
[595] 	}
[596] 
[597] 	public function addPickedupItem(Item $item, bool $ignoreItemCount = false){
[598] 		if(count($this->getPickedupItems()) >= $this->maxPickupableItems and !$this->isCreative() and !$ignoreItemCount){
[599] 			throw new \OutOfRangeException("Items array size cannot be greater than {$this->maxPickupableItems}."); //TODO: ErrStyle fix
[600] 		}
[601] 	
[602] 		$appended = false;
[603] 	
[604] 		// Check if we already picked up the same item and if so append it onto
[605] 		// existing picked up items.
[606] 		foreach ($this->getPickedupItems() as $i) {
[607] 			if ($i->deepEquals($item) and $i->getCount() < $i->getMaxStackSize()) {
[608] 	
[609] 				$amountFree = $i->getMaxStackSize() - $i->getCount();

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)
```
I am using commit 1399 (latest right now)

**Comment by robske110** [comment]
This is due @thebigsmileXD merging a branch wich is known to not work...

**Comment by Aericio** [comment]
```
[12:14:38] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Rabbit Foot (414:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65080070616e63616b65730000
[12:14:38] [Server thread/INFO]: iamanotherkid picked up and placed: Item Rabbit Foot (414:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65080070616e63616b65730000
```
Why is there a tag on this one?

**Comment by Aericio** [comment]
```
[12:15:53] [Server thread/INFO]: hieid picked up and placed: Item Raw Porkchop (319:0)x64
[12:15:53] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650b0052617720506f726b63686f0000
[12:15:53] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650b0052617720506f726b63686f0000
[12:15:53] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650b0052617720506f726b63686f0000
[12:15:53] [Server thread/INFO]: Restoring the statuses of OPs...
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650a0052617720506f726b63680000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650a0052617720506f726b63680000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650a0052617720506f726b63680000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65090052617720506f726b630000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65090052617720506f726b630000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65090052617720506f726b630000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65080052617720506f726b0000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65080052617720506f726b0000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65080052617720506f726b0000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65070052617720506f720000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65070052617720506f720000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65070052617720506f720000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65060052617720506f0000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65060052617720506f0000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65060052617720506f0000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65050052617720500000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65050052617720500000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65050052617720500000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650400526177200000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650400526177200000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650400526177200000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6503005261770000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6503005261770000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6503005261770000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65020052610000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65020052610000
[12:15:54] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65020052610000
[12:15:55] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650100520000
[12:15:55] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650100520000
[12:15:55] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650100520000
[12:15:55] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650100620000
[12:15:55] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650100620000
[12:15:55] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d650100620000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65020062610000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65020062610000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d65020062610000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6503006261630000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6503006261630000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6503006261630000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6504006261636f0000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6504006261636f0000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6504006261636f0000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6505006261636f6e0000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6505006261636f6e0000
[12:15:56] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6505006261636f6e0000
[12:15:58] [Server thread/DEBUG]: PLACEMENT: Full slot of Item Raw Porkchop (319:0)x64 tags:0x0a0300746167030a00526570616972436f7374010000000a0700646973706c61790804004e616d6505006261636f6e0000
[12:15:58] [Server thread/INFO]: hi picked up and placed: Item Raw Porkchop (319:0)x64

Warning: Division by zero in phar://C:/Users/hiitsme/Desktop/Network/ClearSky.phar/src/pocketmine/entity/Human.php on line 219

Warning: Division by zero in phar://C:/Users/whatisthis/Desktop/Network/ClearSky.phar/src/pocketmine/entity/Human.php on line 219

```

**Comment by robske110** [comment]
Will revert and close this issue

**Comment by Aericio** [comment]
:+1:

**Comment by robske110** [comment]
uncaught i will care later

**Comment by thebigsmileXD** [comment]
Just. Fuck. You.

**Comment by robske110** [comment]
good
