### ISSUE TITLE
Fatal error: Uncaught ClassNotFoundException

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#653]
#### ***Crash Message***
```
Fatal error: Uncaught ClassNotFoundException: Class pocketmine\block\Tile not found in phar://C:/Users/fc/Desktop/Network/ClearSky.phar/src/spl/BaseClassLoader.php:128
Stack trace:
#0 [internal function]: BaseClassLoader->loadClass('pocketmine\\bloc...')
#1 phar://C:/Users/fc/Desktop/Network/ClearSky.phar/src/pocketmine/block/MonsterSpawner.php(56): spl_autoload_call('pocketmine\\bloc...')
#2 phar://C:/Users/fc/Desktop/Network/ClearSky.phar/src/pocketmine/level/Level.php(2008): pocketmine\block\MonsterSpawner->place(Object(pocketmine\item\ItemBlock), Object(pocketmine\block\Air), Object(pocketmine\block\RedstoneBlock), 1, 0.505615234375, 1, 0.66845703125, Object(pocketmine\Player))
#3 phar://C:/Users/fc/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(2362): pocketmine\level\Level->useItemOn(Object(pocketmine\math\Vector3), Object(pocketmine\item\ItemBlock), 1, 0.505615234375, 1, 0.66845703125, Object(pocketmine\Player))
#4 phar://C:/Users/fc/Desktop/Network/ClearSky.phar/src/pock in phar://C:/Users/fc/Desktop/Network/ClearSky.phar/src/spl/BaseClassLoader.php on line 128
[11:07:29] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[11:07:29] [Server thread/EMERGENCY]: Please upload the "C:\Users\fc\Desktop\Network\crashdumps/CrashDump_Sun_Aug_7-11.07.29-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
#### ***Crashdump***
```
Error: Uncaught ClassNotFoundException: Class pocketmine\block\Tile not found in phar://C:/Users/420/Desktop/Network/ClearSky.phar/src/spl/BaseClassLoader.php:128
File: /src/spl/BaseClassLoader
Line: 128
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[119] 
[120] 	        if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[121] 		        $name::onClassLoaded();
[122] 	        }
[123] 	        
[124] 	        $this->classes[] = $name;
[125] 
[126]             return true;
[127]         }elseif($this->getParent() === null){
[128] 	        throw new ClassNotFoundException("Class $name not found");
[129]         }
[130] 
[131]         return false;
[132]     }
[133] 
[134]     /**
[135]      * Returns the path for the class, if any
[136]      *
[137]      * @param string $name
[138]      *

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #135 [Protocol 82; API 2.0.0]
uname -a: Windows NT dj-fap 6.2 build 9200 (Windows 8 Home Premium Edition) AMD64
PHP Version: 7.0.9
Zend version: 3.0.0
OS : WINNT, win
```
I know it says **caused by a plugin**, but this wasn't happening before and I didn't download any new plugins. (sincedanstillhatesmeontelegram) Do you know if it really is a plugin? or the ClassLoader or whatever thing.

**Comment by robske110** [comment]
Seems to be the core, wich idiot thinks a folder is a class

**Comment by thebigsmileXD** [comment]
the error starts in 121. name is still no reflection class.
