### ISSUE TITLE
Uncaught TypeError: Argument 2

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#667]
##### ***Crash Message***
```
Notice: Undefined offset: 4 in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php on line 2789

Fatal error: Uncaught TypeError: Argument 2 passed to pocketmine\inventory\ShapedRecipe::setIngredient() must be an instance of pocketmine\item\Item, null given, called in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php on line 2789 and defined in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/inventory/ShapedRecipe.php:93
Stack trace:
#0 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(2789): pocketmine\inventory\ShapedRecipe->setIngredient('e', NULL)
#1 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/network/Network.php(221): pocketmine\Player->handleDataPacket(Object(pocketmine\network\protocol\CraftingEventPacket))
#2 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(1994): pocketmine\network\Network->processBatch(Object(pocketmine\network\protocol\BatchPacket), Object(pocketmine\Player))
#3 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/network/RakLi in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/inventory/ShapedRecipe.php on line 93
[07:48:11] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[07:48:11] [Server thread/EMERGENCY]: Please upload the "C:\Users\hello\Desktop\Network\crashdumps/CrashDump_Sun_Aug_14-07.48.11-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
##### ***CrashDump***
```
ClearSky Crash Dump Sun Aug 14 07:48:11 CEST 2016

Error: Uncaught TypeError: Argument 2 passed to pocketmine\inventory\ShapedRecipe::setIngredient() must be an instance of pocketmine\item\Item, null given, called in phar://C:/Users/hi/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php on line 2789 and defined in phar://C:/Users/bye/Desktop/Network/ClearSky.phar/src/pocketmine/inventory/ShapedRecipe.php:93
File: /src/pocketmine/inventory/ShapedRecipe
Line: 93
Type: E_ERROR

Code:
[84] 	}
[85] 
[86] 	/**
[87] 	 * @param string $key
[88] 	 * @param Item   $item
[89] 	 *
[90] 	 * @return $this
[91] 	 * @throws \Throwable
[92] 	 */
[93] 	public function setIngredient($key, Item $item){
[94] 		if(!array_key_exists($key, $this->shape)){
[95] 			throw new \Throwable("Symbol does not appear in the shape: " . $key);
[96] 		}
[97] 
[98] 		$this->fixRecipe($key, $item);
[99] 
[100] 		return $this;
[101] 	}
[102] 
[103] 	protected function fixRecipe($key, $item){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #177 [Protocol 82; API 2.0.0]
uname -a: Windows NT HALLOITSME 6.2 build 9200 (Windows 8 Home Premium Edition) AMD64
PHP Version: 7.0.9
Zend version: 3.0.0
OS : WINNT, win
```

**Comment by robske110** [comment]
Nothing RakLib
Crafting mess

**Comment by robske110** [comment]
Please provide the steps to produce this :)

**Comment by robske110** [comment]
?

**Comment by Aericio** [comment]
I don't know how to reproduce.

**Comment by Aericio** [comment]
Unless Dan knows something.

**Comment by robske110** [comment]
will be probably fixed due to the most awesome yet perfect dude @dktapps 
I think we can just close all issues :D

**Comment by thebigsmileXD** [comment]
A windows 10 player tried to craft something.
