### ISSUE TITLE
Uncaught Error: Call to a member function getItem() on null

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#668]
#### Breaking Item Frames :D
```
Fatal error: Uncaught Error: Call to a member function getItem() on null in phar://C:/Users/crash/Desktop/Network/ClearSky.phar/src/pocketmine/block/ItemFrame.php:43
Stack trace:
#0 phar://C:/Users/crash/Desktop/Network/ClearSky.phar/src/pocketmine/level/Level.php(1914): pocketmine\block\ItemFrame->onActivate(Object(pocketmine\item\WoodenAxe), Object(pocketmine\Player))
#1 phar://C:/Users/crash/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(2201): pocketmine\level\Level->useItemOn(Object(pocketmine\math\Vector3), Object(pocketmine\item\WoodenAxe), 5, 0.0625, 0.702392578125, 0.480224609375, Object(pocketmine\Player))
#2 phar://C:/Users/crash/Desktop/Network/ClearSky.phar/src/pocketmine/network/Network.php(221): pocketmine\Player->handleDataPacket(Object(pocketmine\network\protocol\UseItemPacket))
#3 phar://C:/Users/crash/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(1994): pocketmine\network\Network->processBatch(Object(pocketmine\network\protocol\BatchPacket), Object(pocketmine\Playe in phar://C:/Users/crash/Desktop/Network/ClearSky.phar/src/pocketmine/block/ItemFrame.php on line 43
[04:48:08] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[04:48:08] [Server thread/EMERGENCY]: Please upload the "C:\Users\crash\Desktop\Network\crashdumps/CrashDump_Mon_Aug_15-04.48.08-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
```
Error: Uncaught Error: Call to a member function getItem() on null in phar://C:/Users/crash/Desktop/Network/ClearSky.phar/src/pocketmine/block/ItemFrame.php:43
File: /src/pocketmine/block/ItemFrame
Line: 43
Type: E_ERROR

Code:
[34] 				new IntTag("x", $this->x),
[35] 				new IntTag("y", $this->y),
[36] 				new IntTag("z", $this->z),
[37] 				new ByteTag("ItemRotation", 0),
[38] 				new FloatTag("ItemDropChance", 1.0)
[39] 			]);
[40] 			Tile::createTile(Tile::ITEM_FRAME, $this->getLevel()->getChunk($this->x >> 4, $this->z >> 4), $nbt);
[41] 		}
[42] 
[43] 		if($tile->getItem()->getId() === 0){
[44] 			$tile->setItem(Item::get($item->getId(), $item->getDamage(), 1));
[45] 			if($player instanceof Player){
[46] 				if($player->isSurvival()) {
[47] 					$count = $item->getCount();
[48] 					if(--$count <= 0){
[49] 						$player->getInventory()->setItemInHand(Item::get(Item::AIR));
[50] 						return true;
[51] 					}
[52] 
[53] 					$item->setCount($count);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #177 [Protocol 82; API 2.0.0]
uname -a: Windows NT clearsky 6.2 build 9200 (Windows 8 Home Premium Edition) AMD64
PHP Version: 7.0.9
Zend version: 3.0.0
OS : WINNT, win
```

**Comment by thebigsmileXD** [comment]
Aaaah.. @beito123 we forgot about removing "air" i guess..
